# Assignment for Analyzing Citibike data
Download citibike trip data from `201701-citibike-tripdata.csv` (<a>https://www.kaggle.com/andytran11996/citibike-dataset-2017#201701-citibike-tripdata.csv</a>) first. This data set contains trips of citibikes in Januaray 2017. In this assignment, we want to explore different patterns of how the number of trips change over time on the New Year's Day. To finish this task, please follow the steps below and provide your final visualizations:
1. Pre-process the data. You can get "hour", "day" of start time. You can do any other processing if you feel it necessary.
2. For each start station, genereate a 24-dimensional vector where each dimension represents the number of rides starting from this station on <strong>January 1st</strong>. For example, there are 609 unique ids, then you should generate a matrix in the shape of (609, 24), where each row is a station and each column is the number of trips started at this hour. 
3. Divide all the stations into several clusters according to the 24-dimensional vectors. You can divide the stations into 5 clusters, or any other number of clusters that makes sense.
4. Visualize the pattern of each cluster individually. And try to answer: How do `number of ride` change over time (hour) in different clusters? You can draw a line chart, or any other chart you think it makes sense, for each cluster.

Hint:

1) must-do: keep the range of y-tick consistent. For example, for each visualization, set the range of y in the visualization from 0 to 35 (`number of trips` from 0 to 35). There are different APIs if you draw the chart using different libraries. (e.g., `ylim`, or `set_yticklabels()` for `matplotlib`, etc.)

2) to make the pattern more clear, you can also set the opacity of each line into 0.1 (the value of `a` for color in the `rgba` format). This is not necessary, but you are encouraged to do this.

5. Provide your answer to: How do stations from different clusters distribute in nyc? For each cluster, please plot the stations in this cluster on a map (you can use heatmap, or any other formats you can show your answer). You may need to do some data transformation to generate this map.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime 
import calendar      
import matplotlib.pyplot as plt
import matplotlib

In [2]:
df = pd.read_csv(filepath_or_buffer="201701-citibike-tripdata.csv",sep=',',
                         header=0, index_col=None, lineterminator='\n')
print(df.shape)

(726676, 15)

In [3]:
df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,680,2017-01-01 00:00:21,2017-01-01 00:11:41,3226,W 82 St & Central Park West,40.782750,-73.971370,3165,Central Park West & W 72 St,40.775794,-73.976206,25542,Subscriber,1965.0,2
1,1282,2017-01-01 00:00:45,2017-01-01 00:22:08,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,21136,Subscriber,1987.0,2
2,648,2017-01-01 00:00:57,2017-01-01 00:11:46,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,18147,Customer,NaN,0
3,631,2017-01-01 00:01:10,2017-01-01 00:11:42,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,21211,Customer,NaN,0
4,621,2017-01-01 00:01:25,2017-01-01 00:11:47,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,26819,Customer,NaN,0